name: testvo
type: VO
resourceType:
  specification: WoT
  version: 1.1
deploymentType: A
catalogue: 9090
bindingNB:
  bindingModeNB: [WS]
  hostname: localhost
  ports:
    websocketPort: 9393
databaseConfig:
  timeseriesDB:
    influxDB: disabled
  persistentDB:
    SQLite: enabled

