imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
ingress:
  enabled: false
resources: {}
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}

thingName: cvo
serviceName: cvo
service:
  type: NodePort
  http:
    port: 8080
    targetPort: 8080
    nodePort: 30021
  catalogue:
    port: 9090
    targetPort: 9090
    nodePort: 30020