apiVersion: apps/v1
kind: Deployment
metadata:
  name: vo2
  labels:
    app: vo2
spec:
  selector:
    matchLabels:
      app: vo2
  template:
    metadata:
      labels:
        app: vo2
    spec:
      containers:
      - name: wotpy
        image: nepheleproject/vo-wot
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: wot-script
            mountPath: /app.py
            subPath: vo_2.py
          - name: wot-config
            mountPath: /config.yaml
            subPath: vo_2.yaml
          - name: wot-td
            mountPath: /td.json
            subPath: vo_2_td.json
        ports:
        - containerPort: 8080
        - containerPort: 5683
        - containerPort: 9090
        readinessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: HOSTNAME
          value: vo2
      volumes:
      - name: wot-script
        hostPath:
          path: /mnt2/
      - name: wot-config
        hostPath:
          path: /mnt2/
      - name: wot-td
        hostPath:
          path: /mnt2/
---
apiVersion: v1
kind: Service
metadata:
  name: vo2
  labels:
    app: vo2
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30010
    protocol: TCP
    name: http
  - port: 5683
    targetPort: 5683
    nodePort: 30012
    protocol: UDP
    name: coap
  - port: 9090
    targetPort: 9090
    nodePort: 30013
    protocol: TCP
    name: catalogue-port
  selector:
    app: vo2
