imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: "vo1"
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
ingress:
  enabled: false
resources: {}
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
deviceURL: "http://192.168.49.1:9090/device1"
brokerIP: "mqtt://192.168.49.1:1883"

thingName: vo1
serviceName: vo1
service:
  type: NodePort
  http:
    port: 8080
    targetPort: 8080
    nodePort: 30001
  catalogue:
    port: 9090
    targetPort: 9090
    nodePort: 30000
