version: "3.9"
   
services:
  mqtt-broker:
    image: eclipse-mosquitto:1.6
    
  wot-py:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a Python version: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local on arm64/Apple Silicon.
        - VARIANT=3.8
        
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
    environment:
      - WOTPY_TESTS_MQTT_BROKER_URL=mqtt://mqtt-broker:1883
    depends_on:
      - mqtt-broker