apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    {{- include "wotpy-influxdb-vo1.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: influx
  selector:
    {{- include "wotpy-influxdb-vo1.selectorLabels" . | nindent 4 }}
